import { useDesignSlice } from '@/store/slices/designSlice'
import { DesignCommands, type DesignCommandContext } from '@/commands/DesignCommands'
import { ALL_COMMANDS } from '@/constants/commands'

const DESIGN_COMMANDS = [
  {
    id: 'design.initialize',
    name: 'design.initialize',
    label: 'Initialize Design Engine',
    description: 'Initialize the design/view engine',
    category: 'design',
    tab: 'datumbim',
    panel: 'core',
    commandType: 'button' as const,
    implementationTarget: 'TASK 003',
    action: 'design.initialize',
    enabled: true,
    visible: true,
    availability: ['always'],
    handler: async (_command: typeof ALL_COMMANDS[0], ctx: DesignCommandContext) =>
      DesignCommands.initialize(ctx),
  },
  {
    id: 'design.dispose',
    name: 'design.dispose',
    label: 'Dispose Design Engine',
    description: 'Dispose the design/view engine',
    category: 'design',
    tab: 'datumbim',
    panel: 'core',
    commandType: 'button' as const,
    implementationTarget: 'TASK 003',
    action: 'design.dispose',
    enabled: true,
    visible: true,
    availability: ['always'],
    handler: async (_command: typeof ALL_COMMANDS[0], ctx: DesignCommandContext) =>
      DesignCommands.dispose(ctx),
  },
  {
    id: 'view.zoomExtents',
    name: 'view.zoomExtents',
    label: 'Zoom Extents',
    description: 'Zoom to fit all elements',
    category: 'view',
    tab: 'view',
    panel: 'navigation',
    commandType: 'button' as const,
    implementationTarget: 'TASK 003',
    action: 'view.zoomExtents',
    enabled: true,
    visible: true,
    availability: ['view-active'],
    handler: async (_command: typeof ALL_COMMANDS[0], ctx: DesignCommandContext) =>
      DesignCommands.zoomExtents(ctx),
  },
  {
    id: 'view.zoomIn',
    name: 'view.zoomIn',
    label: 'Zoom In',
    description: 'Zoom in on the view',
    category: 'view',
    tab: 'view',
    panel: 'navigation',
    commandType: 'button' as const,
    implementationTarget: 'TASK 003',
    action: 'view.zoomIn',
    enabled: true,
    visible: true,
    availability: ['view-active'],
    handler: async (_command: typeof ALL_COMMANDS[0], ctx: DesignCommandContext) =>
      DesignCommands.zoomIn(ctx),
  },
  {
    id: 'view.zoomOut',
    name: 'view.zoomOut',
    label: 'Zoom Out',
    description: 'Zoom out of the view',
    category: 'view',
    tab: 'view',
    panel: 'navigation',
    commandType: 'button' as const,
    implementationTarget: 'TASK 003',
    action: 'view.zoomOut',
    enabled: true,
    visible: true,
    availability: ['view-active'],
    handler: async (_command: typeof ALL_COMMANDS[0], ctx: DesignCommandContext) =>
      DesignCommands.zoomOut(ctx),
  },
  {
    id: 'view.fit',
    name: 'view.fit',
    label: 'Fit to View',
    description: 'Fit selection to view',
    category: 'view',
    tab: 'view',
    panel: 'navigation',
    commandType: 'button' as const,
    implementationTarget: 'TASK 003',
    action: 'view.fit',
    enabled: true,
    visible: true,
    availability: ['view-active', 'selection-exists'],
    handler: async (_command: typeof ALL_COMMANDS[0], ctx: DesignCommandContext) =>
      DesignCommands.fitToView(ctx),
  },
  {
    id: 'selection.select',
    name: 'selection.select',
    label: 'Select',
    description: 'Select an element',
    category: 'selection',
    tab: 'edit',
    panel: 'selection',
    commandType: 'button' as const,
    implementationTarget: 'TASK 003',
    action: 'selection.select',
    enabled: true,
    visible: true,
    availability: ['model-loaded'],
    handler: async (_command: typeof ALL_COMMANDS[0], ctx: DesignCommandContext, elementId?: string) =>
      DesignCommands.selectElement(ctx, elementId ?? ''),
  },
  {
    id: 'selection.clear',
    name: 'selection.clear',
    label: 'Clear Selection',
    description: 'Clear the current selection',
    category: 'selection',
    tab: 'edit',
    panel: 'selection',
    commandType: 'button' as const,
    implementationTarget: 'TASK 003',
    action: 'selection.clear',
    enabled: true,
    visible: true,
    availability: ['selection-exists'],
    handler: async (_command: typeof ALL_COMMANDS[0], ctx: DesignCommandContext) =>
      DesignCommands.clearSelection(ctx),
  },
  {
    id: 'view.setActive',
    name: 'view.setActive',
    label: 'Set Active View',
    description: 'Set the active view',
    category: 'view',
    tab: 'view',
    panel: 'create',
    commandType: 'button' as const,
    implementationTarget: 'TASK 003',
    action: 'view.setActive',
    enabled: true,
    visible: true,
    availability: ['always'],
    handler: async (_command: typeof ALL_COMMANDS[0], ctx: DesignCommandContext, viewId?: string) =>
      DesignCommands.setActiveView(ctx, viewId ?? ''),
  },
  {
    id: 'file.import',
    name: 'file.import',
    label: 'Import',
    description: 'Import a file into the project',
    category: 'file',
    tab: 'datumbim',
    panel: 'core',
    commandType: 'button' as const,
    implementationTarget: 'TASK 005',
    action: 'file.import',
    enabled: true,
    visible: true,
    availability: ['always'],
    handler: async (_command: typeof ALL_COMMANDS[0], ctx: DesignCommandContext) =>
      DesignCommands.openFileImport(ctx),
  },
  {
    id: 'nav.goToLevel',
    name: 'nav.goToLevel',
    label: 'Go to Level',
    description: 'Navigate to a level',
    category: 'navigate',
    tab: 'view',
    panel: 'navigation',
    commandType: 'button' as const,
    implementationTarget: 'TASK 004',
    action: 'nav.level',
    enabled: true,
    visible: true,
    availability: ['view-active'],
    placeholder: true,
    handler: async (_command: typeof ALL_COMMANDS[0], ctx: DesignCommandContext, levelId?: string) =>
      DesignCommands.navigateToLevel(ctx, levelId ?? ''),
  },
  {
    id: 'nav.goToView',
    name: 'nav.goToView',
    label: 'Go to View',
    description: 'Navigate to a view',
    category: 'navigate',
    tab: 'view',
    panel: 'navigation',
    commandType: 'button' as const,
    implementationTarget: 'TASK 004',
    action: 'nav.view',
    enabled: true,
    visible: true,
    availability: ['view-active'],
    placeholder: true,
    handler: async (_command: typeof ALL_COMMANDS[0], ctx: DesignCommandContext, viewId?: string) =>
      DesignCommands.navigateToView(ctx, viewId ?? ''),
  },
]

export const DESIGN_COMMAND_REGISTRY = DESIGN_COMMANDS

export function createDesignCommandContext(): DesignCommandContext {
  return {
    designSlice: useDesignSlice.getState(),
  }
}
